version: '3'

services: 

  github-release:
    image: 'github-release'
    build: './src'

  artifacts:
    image: 'tmvdl/projects:sucht'
    build: './src/app'
    volumes:
      - './src/app:/app'

  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '80:80'
