version: '3'

services:

  speed:
    image: 'tmvdl/projects:speed'
    build: './src/app'
    ports:
      - '80:4200'

  apk:
    image: 'apk'
    build: 
      context: './src'
      dockerfile: 'Dockerfile.apk'

  github-release:
    image: 'github-release'
    build: './src/app'
    volumes:
      - './src/app:/app'

  docker-push:
    image: 'docker-push'
    build: './src/app'
