version: '3'

services: 
  app:
    image: tmvdl/projects:sucht
    build: './src/app'
    volumes:
      - ./src/app:/app
      - ./builds:/builds
  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html/'
    ports:
      - '80:80'
