version: '3'

services: 
  app:
    build: './src/app'
    volumes:
      - './src/app:/app'
      - './builds:/builds'
    ports:
      - '8100:8100'
      - '3000:3000'
    environment:
      - 'CM_KEYSTORE_PATH=keystore'
      - 'CM_KEYSTORE_PASSWORD=keystore'
      - 'CM_KEY_ALIAS=keystore'
      - 'CM_KEY_PASSWORD=keystore'
  www:
    image: 'tmvdl/projects:sucht'
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html/'
    ports:
      - '80:80'
