version: '3'

services: 
  app:
    image: tmvdl/projects:sucht
    build: './src/app'
    volumes:
      - ./src/app:/app
      - ./builds:/builds
    environment:
      - 'CM_KEYSTORE_PATH=keystore'
      - 'CM_KEYSTORE_PASSWORD=keystore'
      - 'CM_KEY_ALIAS=keystore'
      - 'CM_KEY_PASSWORD=keystore'
  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html/'
    ports:
      - '80:80'
