name: GitHub Artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0 * * *'
  push:
    branches: 
      - 'main'

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      # - name: Pull subprojects
      #   run: bash env/pull.sh

      - name: Install packages
        run: bash env/install.sh

      - name: Build Android .apk
        run: bash env/build-app.sh

      - name: Create release
        run: gh release create v$( date +%Y%m%d ) ./src/app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

